### ISSUE TITLE
Doesn't really save, When terminal is closed the process is terminated

### ISSUE THREAD

**Issue by S-codes14** [msaaddev/who-unfollowed-me#1]
It seems as if when ever i close the terminal I have to enter my username again to check, and when that happens it just stores the details, It doesn't tell me who unfollowed me. I am not how this can be fixed with the terminal but if you use the web you can use local storage. I have forked this repo in order to fix the issue, but i am struggling, just wanted to let you know.

**Comment by S-codes14** [comment]
ok now i know that it is for short term use but we can extend that and turn this into something useful, make it long term

**Comment by msaaddev** [comment]
Kindly provide the operating system name and other details like what kind of terminal you are using. I need to update the code a little and I will get to it soon. I use macOS and everything works well there.

**Comment by S-codes14** [comment]
I use ubuntu 20.04  and the builtin terminal
