### ISSUE TITLE
Incomprehensible output

### ISSUE THREAD

**Issue by ComputerScientist-01** [msaaddev/who-unfollowed-me#2]
Using Pop OS 21.04
![Screenshot from 2022-01-09 22-28-56](https://user-images.githubusercontent.com/39644109/148692406-8019d910-2dbb-421a-96f5-9d20fc8ad047.png)

**Comment by ComputerScientist-01** [comment]
So i found out that color.js had been compromised ,
```A developer appears to have purposefully corrupted a pair of open-source libraries on GitHub and software registry npm — “faker.js” and “colors.js” — that thousands of users depend on, rendering any project that contains these libraries useless, as reported by Bleeping Computer.```

**Comment by ComputerScientist-01** [comment]
```
The sabotaged versions cause applications to infinitely output strange letters and symbols, 
beginning with three lines of text that read “LIBERTY LIBERTY LIBERTY.”
```

**Comment by spinF** [comment]
`colors` needs to be pinned to version `1.4.0`, newer versions have been intentionally sabotaged by the developer.

https://github.com/msaaddev/who-unfollowed-me/blob/effd9aad0f02ec5b3316247b1677f750f589ef4e/package.json#L40

See https://github.com/Marak/colors.js/issues/285

**Comment by msaaddev** [comment]
@spinF @ComputerScientist-01 I have launched a new release. Kindly update the CLI and try again.

**Comment by ComputerScientist-01** [comment]
@msaaddev  it works now 👌
