### ISSUE TITLE
maybe update axios dependency?

### ISSUE THREAD

**Issue by owocado** [msaaddev/who-unfollowed-me#4]
Hi,

I was doing my global npm audit today and it notified about vulnerabilites which comes from outdated version of axios lib this is using.

![2022-01-26_13-47-20](https://user-images.githubusercontent.com/24418520/151127645-cc7285cd-5a95-49a3-9882-e48f36bca02d.png)

Hopefully it is possible for you to update this dep. or please close this issue! Thanks and have a nice day!

**Comment by msaaddev** [comment]
Hey! Thanks for the update. I have launched a new [release](https://github.com/msaaddev/who-unfollowed-me/releases/tag/v1.5.1) where I have addressed it.
